### ISSUE TITLE
When loading the object's size before the object's position , the position seems go off the screen

### ISSUE THREAD

**Issue by rustylabs** [AryanpurTech/BlueEngine#23]
If I move the object towards the top left hand side and save it and open it up again, it is fine. however when I suddenly change the size of the object, and save and reopen again, the shape goes off the screen, even though the value of the position is the same. It seems like `5.9` on the y axis is something different if I load the size and the size is different from the default.

Have a look at the gif:

![blue_flame_1m7b3vtwHP](https://user-images.githubusercontent.com/105291856/210235370-3927721b-99eb-4ea4-b271-74c2136c52d7.gif)

**Comment by rustylabs** [comment]
Changing the size back to its original size, saving it and reopening it puts the shape back to its original place.

**Comment by ElhamAryanpur** [comment]
@rustylabs have this been resolved on the pull requests I've made, or is it still an issue?

**Comment by ElhamAryanpur** [comment]
Fixed a little while ago
