### ISSUE TITLE
Change return from tuple to array

### ISSUE THREAD

**Issue by rustylabs** [AryanpurTech/BlueEngine#30]
For example:

```rust
objects
.get(flameobject_label)
.unwrap()
.rotation;
```

this currently returns tuple `(f32, f32, f32)`, please change this to return array `[f32; 3]`.

**Comment by Gipson62** [comment]
I think it returns you a tuple because that's how the rotation field is set up. 
https://github.com/AryanpurTech/BlueEngine/blob/master/src/objects.rs#LL63C1-L63C42
The field rotation is a tuple of 3 f32. It should indeed be a struct of 3 f32 or like you said [f32; 3]. But that's how it works internally. I think @ElhamAryanpur could make something like get_rotation() to return the 3 values in a better way, like `[f32; 3]` or 
```js
Rotation {
  x: f32,
  y: f32,
  z: f32
}
```

**Comment by rustylabs** [comment]
@Gipson62 Yes he is going to do this, I just had a chat with him privately and requested I opened an issue for this request, thank you though!

**Comment by ElhamAryanpur** [comment]
Valid answer by @Gipson62, get_rotation could solve the conflict, however it'll need a set_rotation equally to set values directly without need for the normal rotation function. Which can lead to confusion as one is used for transformation and these are used for keeping track of values...

So imo conversion to array like @rustylabs suggested would be better. Let's see how it goes

**Comment by Gipson62** [comment]
Yeah, I see, maybe on the struct a function like `to_arr()` can exist. It's always better to have higher level constructions if it's something that users will be able to use or manipulate. So a struct is far better than an array and even more than a tuple. And if the `to_arr()` function is inlined (`#[inline]`), the Rust compiler will probably make like it doesn't really exist, with optimisation passes, so the overhead will be very little

**Comment by rustylabs** [comment]
@Gipson62 

> Yeah, I see, maybe on the struct a function like to_arr() can exist.

Agreed and would like to proceed with your suggestion!

> to_arr() function is inlined (#[inline]), the Rust compiler will probably make like it doesn't really exist, with optimisation passes, so the overhead will be very little

Interesting never knew about that, so like why can't every structure be added with this then? What does it exactly do this `#[inline]`?

**Comment by rustylabs** [comment]
@ElhamAryanpur If we do proceed with @Gipson62 suggesting regarding using structure rather than array, then I would like to suggest to add a method which allows you to _set_ the rotation.

**Comment by ElhamAryanpur** [comment]
I'll see what I can do

**Comment by rustylabs** [comment]
@ElhamAryanpur I would also suggest other stuff such as position should also have a structure and should have the same methods as well :)

**Comment by Gipson62** [comment]
@rustylabs 
> Interesting never knew about that, so like why can't every structure be added with this then? What does it exactly do this ``#[inline]``?
When a function is inlined, the compiler takes its body and put it where you call it. For example:

```rs
#[inline]
fn add(a: int, b: int) -> int {
  return a + b;
}

fn main() {
  //This will change
  let x = add(5, 2);
  //and become this:
  let x = 5 + 2;
}
```

And because the function is "exploded" where you call it, the compiler can do various optimization passes to remove a lot of useless stuff or irrelevant stuff based on the context. For example, some conditions can be removed because the context says that a condition is always true. Or some statements/expressions can be removed because never used... And you also remove the overhead of calling a function (creating a new stack frame and modifying some registers for the arguments of the function)

**Comment by rustylabs** [comment]
@Gipson62 But hten why doesn't Rust automatically add these compiler optimisations then?

**Comment by Gipson62** [comment]
@rustylabs the compiler tries to automatically implement these optimizations, but sometimes he can't know whether he should inline or not.

**Comment by ElhamAryanpur** [comment]
oookay finally I'm free to do this

**Comment by rustylabs** [comment]
Cool

-------- Original Message --------

**Comment by ElhamAryanpur** [comment]
fixed by [b74b62672a1377064111f18759704b394dafbd2e](https://github.com/AryanpurTech/BlueEngine/commit/b74b62672a1377064111f18759704b394dafbd2e)

**Comment by ElhamAryanpur** [comment]
I have now used nalgebra-glm's Vec3 structure. So should give you both swizzling and general vector structure as well

**Comment by rustylabs** [comment]
@ElhamAryanpur Has it been comitted to master branch?

**Comment by ElhamAryanpur** [comment]
It is on master branch yes, now pushing it to crates.io

**Comment by rustylabs** [comment]
@ElhamAryanpur So this code:

```rust
Rotation {
  x: f32,
  y: f32,
  z: f32
}
```

this applies to all the other things such as Position, Size etc as well as the methods to the structures?

**Comment by ElhamAryanpur** [comment]
> @ElhamAryanpur So this code:
> 
> ```rust
> Rotation {
>   x: f32,
>   y: f32,
>   z: f32
> }
> ```
> 
> this applies to all the other things such as Position, Size etc as well as the methods to the structures?

Yep! It uses Vec 3 everywhere. Although it's not == Rotation as you wrote above, but it can have fields accessed by .x .y and .z it also have swizzling, like .xy() to give a list of x and y only. Or in different orders too, like .zyx()

**Comment by rustylabs** [comment]
@ElhamAryanpur Interesting, thanks :)

**Comment by ElhamAryanpur** [comment]
Enjoy :)

**Comment by rustylabs** [comment]
@ElhamAryanpur Has it been updated in crates.io, if so can you tell me the current version number of it?

**Comment by rustylabs** [comment]
And what about the egui version @ElhamAryanpur ?

**Comment by ElhamAryanpur** [comment]
Egui version 0.4.4

**Comment by rustylabs** [comment]
@ElhamAryanpur So I assume now we can directly set the Rotation, not just update the rotation?

**Comment by ElhamAryanpur** [comment]
No... It only changed structure, nothing else

**Comment by ElhamAryanpur** [comment]
No... It only changed structure, nothing else

**Comment by ElhamAryanpur** [comment]
> For example:
> 
> ```rust
> objects
> .get(flameobject_label)
> .unwrap()
> .rotation;
> ```
> 
> this currently returns tuple `(f32, f32, f32)`, please change this to return array `[f32; 3]`.

Remember the original issue?

**Comment by rustylabs** [comment]
Yes I do remember this, but the other user has suggested use a Structure instead. Is this what you had done?

And remember how later I suggested to actually have methods for the structure such as "set_rotation", "update_rotation" etc?
------- Original Message -------

**Comment by ElhamAryanpur** [comment]
those things I think remains the same as before. Can set directly just like before if mutable access exist. but I haven't added any extra methods. I forgor

**Comment by rustylabs** [comment]
@ElhamAryanpur Ah right, it would be great to have other things such as `Position` etc added in a structure and have methods such as `set_value()`, `update_value()` etc on which of structures, it keeps everything consistent went either setting or updating either position or rotation, makes it easier to use as well etc.

**Comment by ElhamAryanpur** [comment]
Got it, will do them today if possible, sorry for late response

**Comment by rustylabs** [comment]
All good and thanks

-------- Original Message --------
