### ISSUE TITLE
can no longer build at all

### ISSUE THREAD

**Issue by rustylabs** [AryanpurTech/BlueEngine#51]
Running `cargo r` I get this issue:
```cmd
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/raj/.cargo/registry/src/index.crates.io-6f17d22bba15001f/blue_engine-0.4.28/src/render.rs:59:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ElhamAryanpur** [comment]
I see, please write your OS and environment, I do not know how to reproduce it yet

**Comment by rustylabs** [comment]
I use same os as you man lol

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by rustylabs** [comment]
Moved to 0.5, no longer having issues, closing ticket.

**Comment by rustylabs** [comment]
I am on 0.5 and still issue persists.

**Comment by rustylabs** [comment]
```cmd
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/raj/.cargo/registry/src/index.crates.io-6f17d22bba15001f/blue_engine-0.5.0/src/render.rs:59:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Gipson62** [comment]
This happened because wgpu can't find your GPU, so the engine stops

**Comment by rustylabs** [comment]
@Gipson62 I don't know why doing a ful system update messes chnages my drivers, thanks for letting me know.

**Comment by Gipson62** [comment]
Know that when you get this type of error (in [render.rs line 59](https://github.com/AryanpurTech/BlueEngine/blob/master/src/render.rs#L59 )) it's a GPU error from wgpu. And yeah, sometimes drivers are messed up on some Linux distro because of system updates.

**Comment by ElhamAryanpur** [comment]
Yeah gipson is right, that error is from engine not being able to get access for rendering, which means driver not working correctly

**Comment by rustylabs** [comment]
Yep now working thanks
