### ISSUE TITLE
new keycode key input detection changed/notworking

### ISSUE THREAD

**Issue by NickJasonHagen** [AryanpurTech/BlueEngine#55]
let keyvec = [
    blue_engine::KeyCode::ArrowUp,
    blue_engine::KeyCode::ArrowDown,
    blue_engine::KeyCode::ArrowLeft,
    blue_engine::KeyCode::ArrowRight,
    blue_engine::KeyCode::KeyA,
etc
    let keyname = [ // keymapping naming ( must contain the same size and order as the keymapping!!)
    "key.up",
    "key.down",
    "key.left",
    "key.right",
    "key.a",
etc
];
            // Keyboard-input bridge , registers key.* classproperties to down or up
            let mut idx = 0;
            for xkey in keyname{
                if input.key_pressed(keyvec[idx]) {
                    vmap.setvar(keyname[idx].to_owned(),"down");
                    vmap.setvar("key.event".to_owned(),"true");
                    cwrite(&keyname[idx],"y")
                }
                else{
                    vmap.setvar(keyname[idx].to_owned(),"up");
                }
                idx +=1;
            }
            
    --------------------------------------------
    key_pressed nor held_down is working, got some idea's ? worked before the last update

**Comment by ElhamAryanpur** [comment]
fixed by `0.5.2`
