### ISSUE TITLE
GT730M DX11 /GL/Vulkan issues crashing after first frame.

### ISSUE THREAD

**Issue by NickJasonHagen** [AryanpurTech/BlueEngine#61]
Error in surface::configure: Validation Error

caused by  : Parent device is lost
failed to create device requestdevice error { inner: Core(limitexcee(Faillimit { Name: "Max_compute_workougroups_pe
_dimensions, requested: 65535, allowed : 0 

Hardware : 
i7 3610QM
16gb ddr3 1600
mPCI-SSD
GT730m 2GB

Windows: 10

**Comment by ElhamAryanpur** [comment]
Related to line 62 render.rs limits, I gotta change it to downgrade or give option to do so
